### ISSUE TITLE
Crear un servicio REST con Python (Django?)

### ISSUE THREAD

**Issue by mpericay** [mpericay/tm3#153]
Query: 
select count(*)," + taxon.levelsId[childrenLevel] + " as id," + taxon.levels[childrenLevel] + " as name" + parent + " from mcnb_prod WHERE " + taxon.levelsId[level] + "='"+ taxon.getChild()['id'] +"'" + getFiltersSQL(filters, ["circle", "fieldvalue", "minmax"]) + " group by id, name, parent order by count(*) desc"

Ej: 
SELECT COUNT(*), domain,kingdom,phylum,class,_order,family,familyid,genus,genusid FROM mcnb_prod where familyid='Rodentia:Cricetidae' AND basisofrecord='Fossil' group by domain,kingdom,phylum,class,_order,family,familyid,genus,genusid order by count(*) desc

JSON:
 [
  {
    "id": "Animalia",
    "name": "Animalia",
    "parent": "Eukaryota",
    "children": [
      {
        "id": "Chordata",
        "name": "Chordata",
        "parent": "Animalia",
        "children": [
          {
            "id": "Mammalia",
            "name": "Mammalia",
            "parent": "Chordata",
            "children": [
              {
                "id": "Rodentia",
                "name": "Rodentia",
                "parent": "Mammalia",
                "children": [
                  {
                    "id": "Rodentia:Cricetidae",
                    "count": 748,
                    "name": "Cricetidae",
                    "parent": "Rodentia",
                    "children": [
                      {
                        "id": "Rodentia:Cricetidae:Apocricetus",
                        "count": 713,
                        "name": "Apocricetus",
                        "parent": "Rodentia:Cricetidae"
                      },
                      {
                        "id": "Rodentia:Cricetidae:Tragomys",
                        "count": 35,
                        "name": "Tragomys",
                        "parent": "Rodentia:Cricetidae"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
]

JSON alternativo (si el anterior no es fácil):
{
  "rows": [
    {
      "count": 713,
      "domain": "Eukaryota",
      "kingdom": "Animalia",
      "phylum": "Chordata",
      "class": "Mammalia",
      "_order": "Rodentia",
      "family": "Cricetidae",
      "familyid": "Rodentia:Cricetidae",
      "genus": "Apocricetus",
      "genusid": "Rodentia:Cricetidae:Apocricetus"
    },
    {
      "count": 35,
      "domain": "Eukaryota",
      "kingdom": "Animalia",
      "phylum": "Chordata",
      "class": "Mammalia",
      "_order": "Rodentia",
      "family": "Cricetidae",
      "familyid": "Rodentia:Cricetidae",
      "genus": "Tragomys",
      "genusid": "Rodentia:Cricetidae:Tragomys"
    }
  ]
}

**Comment by michogar** [comment]
Me vendrían bien los modelos de Carto para crear las tablas en la base de datos. ¿Puedes pasarmelos?. SI lo tienes en SQL o dame acceso a Carto.

**Comment by mpericay** [comment]
Es una sola tabla, mcnb_prod, no hay modelo de datos. Es como trabajan en el GBIF. Te envío CSV por mail.

**Comment by michogar** [comment]
Si, había visto que era solo una table, pero necesito la definición de los campos.

Merçi

**Comment by michogar** [comment]
Vale, sorry, ya lo tenía. Me lo habías enviado al correo. Perdona

**Comment by michogar** [comment]
```sql
CREATE TABLE public.mcnb_prod (
    typestatus character varying(255),
    identificationqualifier character varying(255),
    dateidentified character varying(255),
    identifiedby character varying(255),
    georeference_validated character varying(255),
    year character varying(255),
    month character varying(255),
    day character varying(255),
    maximumdepthinmeters character varying(255),
    minimumdepthinmeters character varying(255),
    maximumelevationinmeters character varying(255),
    minimumelevationinmeters character varying(255),
    individualcount character varying(255),
    dayidentified character varying(255),
    monthidentified character varying(255),
    yearidentified character varying(255),
    subspecies character varying(255),
    species character varying(255),
    domain character varying(255),
    subspeciesid character varying(255),
    speciesid character varying(255),
    genusid character varying(255),
    familyid character varying(255),
    taxonrank character varying(255),
    scientificnameauthorship character varying(255),
    infraspecificepithet character varying(255),
    specificepithet character varying(255),
    subgenus character varying(255),
    genus character varying(255),
    family character varying(255),
    _order character varying(255),
    class character varying(255),
    phylum character varying(255),
    kingdom character varying(255),
    scientificname character varying(255),
    cartodb_id integer,
    geodeticdatum character varying(255),
    islandgroup character varying(255),
    island character varying(255),
    waterbody character varying(255),
    verbatimlocality character varying(255),
    locality character varying(255),
    municipality character varying(255),
    county character varying(255),
    stateprovince character varying(255),
    countrycode character varying(255),
    country character varying(255),
    continent character varying(255),
    eventremarks character varying(255),
    samplingprotocol character varying(255),
    habitat character varying(255),
    verbatimeventdate character varying(255),
    eventdate character varying(255),
    fieldnumber character varying(255),
    occurrenceid character varying(255),
    previousidentifications character varying(255),
    associatedoccurrences character varying(255),
    othercatalognumbers character varying(255),
    associatedreferences character varying(255),
    preparations character varying(255),
    lifestage character varying(255),
    sex character varying(255),
    recordedby character varying(255),
    recordnumber character varying(255),
    catalognumber character varying(255),
    basisofrecord character varying(255),
    collectioncode character varying(255),
    institutioncode character varying(255),
    coordinateuncertaintyinmeters character varying(255),
    decimallongitude real,
    decimallatitude real,
    geom public.geometry(Point,4326)
);
```

**Comment by mpericay** [comment]
Pues no es del todo correcto, hay 5-6 campos más que son numéricos (year, month, day y alguno más) y georeference_validated es booleano. El usuario de carto es "mcnb" te paso pwd por whatss

**Comment by michogar** [comment]
Pues esa SQL la he sacado de lo que me has pasado tú. Parece un backup de la base de datos.

[mcnb_prod.sql.zip](https://github.com/mpericay/tm3/files/3396023/mcnb_prod.sql.zip)

**Comment by mpericay** [comment]
Sorry, ellos trabajan subiendo y bajando CSV con lo que periódicamente vuelven los character varying(255) y hay que rehacer a mano. En cualquier caso, lo puedo cambiar después, no te preocupes. Solo que year, month, day sean numéricos ya va bien.

**Comment by michogar** [comment]
Respuesta:

```json
[{
	"id": "Animalia",
	"name": "Animalia",
	"parent": "Eukaryota",
	"children": [{
		"id": "Chordata",
		"name": "Chordata",
		"parent": "Animalia",
		"children": [{
			"id": "Mammalia",
			"name": "Mammalia",
			"parent": "Chordata",
			"children": [{
				"id": "Rodentia",
				"name": "Rodentia",
				"parent": "Mammalia",
				"children": [{
					"id": "Rodentia:Cricetidae",
					"count": 748,
					"name": "Cricetidae",
					"parent": "Rodentia",
					"children": [{
							"id": "Rodentia:Cricetidae:Apocricetus",
							"count": 713,
							"name": "Apocricetus",
							"parent": "Rodentia:Cricetidae"
						},
						{
							"id": "Rodentia:Cricetidae:Tragomys",
							"count": 35,
							"name": "Tragomys",
							"parent": "Rodentia:Cricetidae"
						}
					]
				}]
			}]
		}]
	}]
}]
```

**Comment by mpericay** [comment]
Parece perfecto

**Comment by michogar** [comment]
```sql
copy api_mcbnprod(typestatus, identificationqualifier, dateidentified, identifiedby, 
            georeference_validated, year, month, day, maximumdepthinmeters, 
            minimumdepthinmeters, maximumelevationinmeters, minimumelevationinmeters, 
            individualcount, dayidentified, monthidentified, yearidentified, 
            subspecies, species, domain, subspeciesid, speciesid, genusid, 
            familyid, taxonrank, scientificnameauthorship, infraspecificepithet, 
            specificepithet, subgenus, genus, family, _order, _class, phylum, 
            kingdom, scientificname, geodeticdatum, islandgroup, island, 
            waterbody, verbatimlocality, locality, municipality, county, 
            stateprovince, countrycode, country, continent, eventremarks, 
            samplingprotocol, habitat, verbatimeventdate, eventdate, fieldnumber, 
            occurrenceid, previousidentifications, associatedoccurrences, 
            othercatalognumbers, associatedreferences, preparations, lifestage, 
            sex, recordedby, recordnumber, catalognumber, basisofrecord, 
            collectioncode, institutioncode, coordinateuncertaintyinmeters, 
            decimallongitude, decimallatitude, geom)
from '/home/michogarcia/Escritorio/mcnb_prod_backup20190603.csv' DELIMITER ',' CSV HEADER;
```

**Comment by michogar** [comment]
Copia de la base de datos:

[mcnb_prod.sql.zip](https://github.com/mpericay/tm3/files/3396758/mcnb_prod.sql.zip)

**Comment by michogar** [comment]
He importado la tabla en la base de datos y he migrado los datos a la nueva tabla:

```sql
insert into api_mcbnprod SELECT cartodb_id, typestatus, identificationqualifier, dateidentified, identifiedby, 
       georeference_validated, nullif(year, '')::int, nullif(month, '')::int, nullif(day, '')::int, maximumdepthinmeters, 
       minimumdepthinmeters, maximumelevationinmeters, minimumelevationinmeters, 
       individualcount, dayidentified, monthidentified, yearidentified, 
       subspecies, species, domain, subspeciesid, speciesid, genusid, 
       familyid, taxonrank, scientificnameauthorship, infraspecificepithet, 
       specificepithet, subgenus, genus, family, _order, class, phylum, 
       kingdom, scientificname, geodeticdatum, islandgroup, 
       island, waterbody, verbatimlocality, locality, municipality, 
       county, stateprovince, countrycode, country, continent, eventremarks, 
       samplingprotocol, habitat, verbatimeventdate, eventdate, fieldnumber, 
       occurrenceid, previousidentifications, associatedoccurrences, 
       othercatalognumbers, associatedreferences, preparations, lifestage, 
       sex, recordedby, recordnumber, catalognumber, basisofrecord, 
       collectioncode, institutioncode, coordinateuncertaintyinmeters, 
       decimallongitude, decimallatitude, geom
  FROM public.mcnb_prod
```

**Comment by michogar** [comment]
La consulta 

```sql
SELECT COUNT(*), domain,kingdom,phylum,class,_order,family,familyid,genus,genusid FROM mcnb_prod where familyid='Rodentia:Cricetidae' AND basisofrecord='Fossil' group by domain,kingdom,phylum,class,_order,family,familyid,genus,genusid order by count(*) desc
```

devuelve

```
713;"Eukaryota";"Animalia";"Chordata";"Mammalia";"Rodentia";"Cricetidae";"Rodentia:Cricetidae";"Apocricetus";"Rodentia:Cricetidae:Apocricetus"
35;"Eukaryota";"Animalia";"Chordata";"Mammalia";"Rodentia";"Cricetidae";"Rodentia:Cricetidae";"Tragomys";"Rodentia:Cricetidae:Tragomys"
```

**Comment by mpericay** [comment]
Correcto: 713 ratitas y 35 hamsters

**Comment by michogar** [comment]
Hay un repo con la API

https://github.com/northings/restmuseum/

Te he mandado invitación. Échale un vistazo y comentamos.

**Comment by mpericay** [comment]
Closed by https://github.com/mpericay/tm3/commit/94a3683ea2f7c8844112fea4052439b2a8322fa4
